### ISSUE TITLE
PROGRAM EXITS AFTER HITTING ENTER AND THE READLINE IS EMPTY

### ISSUE THREAD

**Issue by ibranad** [ibranad/Minishell_42#10]
Double prompt after SIGINT when the program hangs
<a href="https://ibb.co/wgVRpwN"><img src="https://i.ibb.co/1Q1LRdf/Screen-Shot-2022-10-24-at-10-17-43-AM.png" alt="Screen-Shot-2022-10-24-at-10-17-43-AM" border="0"></a>

**Comment by OussamaBOUIZ** [comment]
I'm working on it

**Comment by OussamaBOUIZ** [comment]
I still have no idea, about what's causing this, along with other weird behaviors of the prompt.

**Comment by OussamaBOUIZ** [comment]
`Control-C` works so far decently. But I noticed that the programs PROGRAM EXITS AFTER HITTING ENTER AND THE READLINE IS EMPTY

**Comment by OussamaBOUIZ** [comment]
**PROGRAM EXITS AFTER HITTING ENTER AND THE READLINE IS EMPTY**  
This issue was due to the bad conditions management in the `parser` function. 
**Fix :** After filling the `red_line` by the `readline()` call, we make sure first that `char *red_line` holds a valid address and that it's not an empty string `if (red_line && *red_line)` if so we proceed for the parsing of that returned string. If no, we check if it's about an invalid address `0x0` so `red_line` is `NULL` and this indicates that the `readline` read an EOF (Control-D) in this case we should exit the shell. Else undoubtedly this `*red_line` is `FALSE` so it holds the null character which means that the user hit Enter on an empty prompt, which should result in prompting the user again.
