### ISSUE TITLE
Uppercase Lowercase issue

### ISSUE THREAD

**Issue by ibranad** [ibranad/Minishell_42#2]
**Uppercase**
When entering this command for example `echo$USER` it should output in bash `var_value` whereas in mini shell it outputs `$user`

**Comment by OussamaBOUIZ** [comment]
This is due to the `str_tolower` method which we called before expanding the whole string. This issue reminds me of an important concern 💡 . You know if we used to lowercase the whole command line, it'll produces other problems for example
you may want to create a file with this name : `FiLe` we'll create `file`. The reason that made us to lower is to get the path of a given command. Hence this should be exclusive for command names only.

**Comment by ibranad** [comment]
This problem was fixed , the solution was to lower command when parsing only not the entire input string
