### ISSUE TITLE
Double prompt is still not fixed

### ISSUE THREAD

**Issue by ibranad** [ibranad/Minishell_42#24]
Double prompt after SIGINT

<img width="346" alt="Screen Shot 2022-10-29 at 11 20 47 AM" src="https://user-images.githubusercontent.com/57199774/198826158-0989cd6a-61b1-4556-9e47-5ecf83c9478a.png">

**Comment by OussamaBOUIZ** [comment]
**IT'S FIXED NOW:**
<img width="215" alt="Screen Shot 2022-11-01 at 5 55 59 PM" src="https://user-images.githubusercontent.com/65982891/199291513-e9ba1055-2118-4cb0-9808-6c4d85810719.png">

**Comment by OussamaBOUIZ** [comment]
The problem was presented as follows:
The handling of signals and most precisely the SIGINT, gets affected with the stage of program execution,  so if the `readline()` did not yet read anything; hitting `Control-C` should output a new_line and proceed for `rl_redisplay()` call to get that a new prompt. In contrast when the `readline()` has already read something into the `line_buffer` the programs execute it for example here `cat` which start reading from STDIN  and it exits when receiving a SIGINT this would automatically displays the `Minishell $>` so there's no need to redisplay it. That's it
