### ISSUE TITLE
Program hangs in case of 'cat | cat | ls'

### ISSUE THREAD

**Issue by ibranad** [ibranad/Minishell_42#29]
When inserting this command  `cat | cat | ls` the program hangs  waiting for input
### bash :
<img width="407" alt="Screen Shot 2022-10-31 at 2 12 10 PM" src="https://user-images.githubusercontent.com/57199774/199016718-bd851271-6224-4cbf-8eba-41905e7cd28e.png">

**Comment by OussamaBOUIZ** [comment]
I'll check it now

**Comment by OussamaBOUIZ** [comment]
actually it does not hang, the cat reads from stdin till it gets the EOF .

**Comment by OussamaBOUIZ** [comment]
This issue was fixed a few days ago, true a closing of the stdin file descriptor in the child process that is responsible for running the last process. We came up with this solution after doing some troubleshooting with the `lsof` tool that list the open fildes in a given process, and also after reading about the behavior of the `cat` command combined in a pipeline with a command that does not need a input stream. But for me this does not make sense 100%. This issue would be  open in future to add more insights
