### ISSUE TITLE
Command with space at end of it

### ISSUE THREAD

**Issue by ibranad** [ibranad/Minishell_42#3]
### Lexer issue when adding space a the end
When entering command like `"ls -la"` it outputs `(nature: 6, lexeme: ls) (nature: 6, lexeme: -la)` but when adding space at the end of command `"ls -la "` it outputs `(nature: 6, lexeme: ls) (nature: 6, lexeme: (null))` which results in a segfault when calling the parsing list function cause lexeme will contain NULL in this case

**Comment by OussamaBOUIZ** [comment]
Okay, I'll check it for now

**Comment by OussamaBOUIZ** [comment]
The Bug was Fixed.
he Bug: when lexing a line ending with whitespaces, the lexer goes to the character after which
is the end of the line and lex it as a _word lexeme pointing to NULL
 The Fix: when reading the character that comes after whitespaces, the program make sure that it's NOT the null character '\0' before proceeding to its tokenization
