### ISSUE TITLE
Scrambled Output

### ISSUE THREAD

**Issue by ibranad** [ibranad/Minishell_42#40]
We get scrambled output when entering this command **`echo "hello > out | cat -e"`** which could potentially indicate that there is a problem with pipes

<img width="500" alt="Screen Shot 2022-11-05 at 6 49 52 PM" src="https://user-images.githubusercontent.com/57199774/200136093-1f939ec3-dba1-45c3-bfdb-8ab2c21669b6.png">

**Comment by OussamaBOUIZ** [comment]
The way I've implemented the spacing between `echo` arguments was responsible of this issue. Precisely i was printing the value of a char variable `c` that i set as `c = 32` and in case i'm printing the last argument i reset it to `c = 0`. When running `cat -e out` it converts the null-terminating character to `^@`. so the fix was about the spacing implementation as below:
```
while (i < ac)
{
   if (i == ac - 1)
       printf("%s", av[i++]);
   else
	printf("%s ", av[i++]);
}
```
