### ISSUE TITLE
⚠️ Segfault when getting input from pipe

### ISSUE THREAD

**Issue by ibranad** [ibranad/Minishell_42#7]
When inserting a command like this for example in bash `echo hello | ./minishell` the program  crashes

**Comment by OussamaBOUIZ** [comment]
It seems that this caused by the readline!! I'll see about it

**Comment by OussamaBOUIZ** [comment]
The `minishell` actually needs the `char   **env` arguments for its functioning, it uses it to set up the ENV variable in order to fetch commands paths and much more... . When running `./minishell`, it accesses the environment list  using the global variable `char **env`. If we type in the prompt yielded by `./minishell` this given command `echo hello | ./minishell`, this last word would be treated as a command and hence it gets executed through the `execve()` syscall, the  last parameter of this call is supposed to be the `char **env` which was set to `NULL` beforehand, the thing that causes the SEGV.  By passing the `env` along till the `execve`, we prevent this issue and refine the behavior of our program.
